imports:
    - php

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths: [vendor/*, test/*]

build:

    dependencies:
        before:
            -
                command: "mkdir build"

    tests:
        override:
            -
                command: "phpunit --configuration .phpunit.xml"
                # coverage:
                #     file: "build/coverage.clover"
                #     format: "php-clover"
